spring:
  application:
    name:  shiro-token
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true
      username: root
      password: root
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
      stat-view-servlet:         #开启web监控页面
        url-pattern: /druid/*  #web访问路径
        allow: localhost       #允许访问的ip,不配置默认所有地址都可以访问
        login-username: admin  #访问需要的用户名
        login-password: 123654 #访问需要的密码
      web-stat-filter:    #配置web过滤器
        url-pattern: /*   #过滤url
        exclusions: /druid/*  #排除过滤
server:
  port: 8088
