spring:
  mail:
    #如果是163  就为  smtp.163.com
    host: smtp.qq.com
    #刚才开通了SMTP的QQ邮箱
    username: 746329807@qq.com
    # 在页面生成的授权码
    password: elxabcbcaplobajb
    default-encoding: utf-8
    protocol: smtp
    # 默认端口
    port: 25
    properties:
      mail:
        smtp:
          # 设置是否需要认证，如果为true,那么用户名和密码就必须的，
          # 如果设置false，可以不设置用户名和密码，当然也得看你的对接的平台是否支持无密码进行访问的。
          auth: true
          starttls:
            # STARTTLS[1]  是对纯文本通信协议的扩展。它提供一种方式将纯文本连接升级为加密连接（TLS或SSL），而不是另外使用一个端口作加密通信。
            enable: true
            required: true
