server:
  port: 8021
spring:
  application:
    name: rabbitmq-provider
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

    publisher-confirms: true

    publisher-returns: true

#    //具体参看了配置的源码
#    org.springframework.boot.autoconfigure.amqp.RabbitProperties


#    //RabbitMQ单机
#    spring:
#      rabbitmq:
#        host: localhost
#        port: 5672
#        username: your_username
#        password: your_password

#    //或者  RabbitMQ单机，只使用addresses
#    spring:
#      rabbitmq:
#        addresses:ip1:port1
#        username: your_username
#        password: your_password


#    //RabbitMQ集群，addresses一定要逗号分隔
#    spring:
#      rabbitmq:
#        addresses:ip1:port1,ip2:port2,ip3:port3
#        username: your_username
#        password: your_password