server:
  port: 8021
spring:
  application:
    name: rabbitmq-provider
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#    publisher-confirms: true
    publisher-confirm-type: correlated
    publisher-returns: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
