server:
    port: 8080
spring:
    redis:
        host: 192.168.14.38
#        host: 39.108.10.101
        port: 6379
        database: 0
        password: hthl@2018
        lettuce:
            pool:
                max-active: 8
                max-wait: -1
                max-idle: 8
                min-idle: 0
    redis2:
        host: 192.168.14.38
        #        host: 39.108.10.101
        port: 6379
        database: 2