fdfs:
  soTimeout: 1500         #
  connectTimeout: 600
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  trackerList:            #TrackerList参数,支持多个
#    - 172.18.105.12:22122
    - 39.108.10.101:22122
    #     - 172.18.105.13:22122
    #内网地址 (http://172.18.105.5:8080/)
    #外网地址
#  httpurl: http://www.htgt.cn:8721/
spring:
  thymeleaf:
    prefix: classpath:/static/
    cache: false
    encoding: utf-8
    suffix: .html