server:
  port: 8089
spring:
  data:
    mongodb:
      database: test1
      host: 127.0.0.1
      port: 27017
#      uri: mongodb://账户:密码IP:27017,10.3.0.21:27017,10.3.0.9:27017/cps_view?replicaSet=foobar&authSource=admin
